# Generated by Django 3.2 on 2023-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(null=True, verbose_name='Y-m-d'),
        ),
    ]
