# Generated by Django 4.1.1 on 2023-01-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
