# Generated by Django 3.2 on 2023-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post3',
            name='tag3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
