# Generated by Django 4.1.1 on 2023-01-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post9',
            fields=[
                ('post_code9', models.AutoField(primary_key=True, serialize=False)),
                ('date9', models.DateField()),
                ('name9', models.CharField(max_length=100)),
                ('letter9', models.TextField()),
                ('image9', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags9', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post8',
            fields=[
                ('post_code8', models.AutoField(primary_key=True, serialize=False)),
                ('date8', models.DateField()),
                ('name8', models.CharField(max_length=100)),
                ('letter8', models.TextField()),
                ('image8', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags8', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post7',
            fields=[
                ('post_code7', models.AutoField(primary_key=True, serialize=False)),
                ('date7', models.DateField()),
                ('name7', models.CharField(max_length=100)),
                ('letter7', models.TextField()),
                ('image7', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags7', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post6',
            fields=[
                ('post_code6', models.AutoField(primary_key=True, serialize=False)),
                ('date6', models.DateField()),
                ('name6', models.CharField(max_length=100)),
                ('letter6', models.TextField()),
                ('image6', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags6', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post5',
            fields=[
                ('post_code5', models.AutoField(primary_key=True, serialize=False)),
                ('date5', models.DateField()),
                ('name5', models.CharField(max_length=100)),
                ('letter5', models.TextField()),
                ('image5', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags5', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post4',
            fields=[
                ('post_code4', models.AutoField(primary_key=True, serialize=False)),
                ('date4', models.DateField()),
                ('name4', models.CharField(max_length=100)),
                ('letter4', models.TextField()),
                ('image4', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags4', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post3',
            fields=[
                ('post_code3', models.AutoField(primary_key=True, serialize=False)),
                ('date3', models.DateField()),
                ('name3', models.CharField(max_length=100)),
                ('letter3', models.TextField()),
                ('image3', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags3', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('post_code2', models.AutoField(primary_key=True, serialize=False)),
                ('date2', models.DateField()),
                ('name2', models.CharField(max_length=100)),
                ('letter2', models.TextField()),
                ('image2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags2', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post12',
            fields=[
                ('post_code12', models.AutoField(primary_key=True, serialize=False)),
                ('date12', models.DateField()),
                ('name12', models.CharField(max_length=100)),
                ('letter12', models.TextField()),
                ('image12', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags12', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post11',
            fields=[
                ('post_code11', models.AutoField(primary_key=True, serialize=False)),
                ('date11', models.DateField()),
                ('name11', models.CharField(max_length=100)),
                ('letter11', models.TextField()),
                ('image11', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags11', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post10',
            fields=[
                ('post_code10', models.AutoField(primary_key=True, serialize=False)),
                ('date10', models.DateField()),
                ('name10', models.CharField(max_length=100)),
                ('letter10', models.TextField()),
                ('image10', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('tags10', models.ManyToManyField(blank=True, to='shop.tag')),
            ],
        ),
    ]
